#pragma once
#include <Eigen/Dense>
#include <vector>
#include <utility>
#include <iostream>  
#include <string>
#include <nanoflann.hpp>
#include "nanoflann.h"
#include <unsupported/Eigen/MatrixFunctions>
#include <limits>
#include <type_traits>
#include <time.h>
#include <fstream>
#include <algorithm>
#include <Eigen/Sparse>
#include <OpenMesh/Core/Geometry/VectorT.hh>
#include <OpenMesh/Core/Mesh/TriMesh_ArrayKernelT.hh>
#include <OpenMesh/Core/IO/MeshIO.hh>
#include <cmath>
#include "Types.h"
#include "OmpHelper.h"